apb_stream: fix savings callback processing
Added an extra read to avoid rounding errors in callbacks for non-object values:

```
[E 2021-02-12 15:29:35,883.883 ophyd.objects  ophydobj:467] Subscription value callback exception (EpicsSignal(read_pv='XF:08IDB-CT{PBA:1}:FA:Stream:Bin:File:Status-I', name='apb_stream_filebin_status', parent='apb_stream', value=0, timestamp=1613161463.141703, auto_monitor=False, string=False, write_pv='XF:08IDB-CT{PBA:1}:FA:Stream:Bin:File:Status-I', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/opt/conda_envs/collection-2021-1.0/lib/python3.7/site-packages/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/opt/conda_envs/collection-2021-1.0/lib/python3.7/site-packages/ophyd/status.py", line 679, in check_value
    success = self.callback(*args, **kwargs)
  File "/home/xf08id/.ipython/profile_collection/startup/29-apb.py", line 214, in callback_saving
    if int(round(old_value)) == 1 and int(round(value)) == 0:
TypeError: type object doesn't define __round__ method
[E 2021-02-12 15:29:35,885.885 ophyd  status:683] type object doesn't define __round__ method
[E 2021-02-12 15:29:35,885.885 ophyd.objects  ophydobj:467] Subscription value callback exception (EpicsSignal(read_pv='XF:08IDB-CT{PBA:1}:FA:Stream:Txt:File:Status-I', name='apb_stream_filetxt_status', parent='apb_stream', value=0, timestamp=1613161463.141797, auto_monitor=False, string=False, write_pv='XF:08IDB-CT{PBA:1}:FA:Stream:Txt:File:Status-I', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/opt/conda_envs/collection-2021-1.0/lib/python3.7/site-packages/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/opt/conda_envs/collection-2021-1.0/lib/python3.7/site-packages/ophyd/status.py", line 679, in check_value
    success = self.callback(*args, **kwargs)
  File "/home/xf08id/.ipython/profile_collection/startup/29-apb.py", line 214, in callback_saving
    if int(round(old_value)) == 1 and int(round(value)) == 0:
TypeError: type object doesn't define __round__ method
```